// 安颐家商城 - 适老化家具商品数据

export const shopCategories = [
  { key: 'all', label: '全部商品' },
  { key: 'bathroom', label: '卫浴安全' },
  { key: 'bedroom', label: '卧室适老' },
  { key: 'living', label: '客厅安全' },
  { key: 'kitchen', label: '厨房适老' },
  { key: 'lighting', label: '智能照明' },
  { key: 'assist', label: '辅助器具' },
];

export const products = [
  // === 卫浴安全 ===
  {
    id: 'p001',
    name: '适老安全扶手（L型）',
    desc: '304不锈钢，防滑纹理，承重150kg，马桶旁/淋浴区通用',
    category: 'bathroom',
    price: 268,
    originalPrice: 398,
    tags: ['热销', '包邮'],
    specs: '长度60cm / 颜色：哑光白、香槟金',
    cover: '/shop_img/handrail_l.jpg',
  },
  {
    id: 'p002',
    name: '防滑地砖（适老专用）',
    desc: 'R11级防滑，哑光表面，多色可选，全屋适用',
    category: 'bathroom',
    price: 89,
    originalPrice: 128,
    tags: ['新品'],
    specs: '300×300mm / 厚度8mm',
    cover: '/shop_img/anti_slip_tile.jpg',
  },
  {
    id: 'p003',
    name: '坐式淋浴椅（折叠款）',
    desc: '铝合金框架，承重150kg，折叠收纳不占空间，防滑脚垫',
    category: 'bathroom',
    price: 458,
    originalPrice: 598,
    tags: ['热销'],
    specs: '座高38-53cm可调 / 宽42cm',
    cover: '/shop_img/shower_chair.jpg',
  },
  {
    id: 'p004',
    name: '恒温防烫花洒套装',
    desc: '38°C恒温锁定，防烫伤设计，大面板雨淋+手持双模式',
    category: 'bathroom',
    price: 688,
    originalPrice: 888,
    tags: ['推荐'],
    specs: '面板直径25cm / 恒温阀芯',
    cover: '/shop_img/thermostat_shower.jpg',
  },
  {
    id: 'p005',
    name: '智能马桶（适老款）',
    desc: '自动翻盖、座圈加热、暖风烘干、一键冲洗，适老遥控器',
    category: 'bathroom',
    price: 3280,
    originalPrice: 4580,
    tags: ['热销', '包邮'],
    specs: '即热式 / 坑距300/400mm',
    cover: '/shop_img/smart_toilet.jpg',
  },

  // === 卧室适老 ===
  {
    id: 'p006',
    name: '适老电动护理床',
    desc: '电动升降背腿，防跌落护栏，万向轮可锁定，静音电机',
    category: 'bedroom',
    price: 4680,
    originalPrice: 5980,
    tags: ['包邮', '上门安装'],
    specs: '1.5m/1.8m / 承重200kg',
    cover: '/shop_img/nursing_bed.jpg',
  },
  {
    id: 'p007',
    name: '床边安全扶手（单侧）',
    desc: '免打孔安装，U型稳固底座，起身助力，高度可调',
    category: 'bedroom',
    price: 328,
    originalPrice: 458,
    tags: ['热销'],
    specs: '高度55-75cm可调 / 管径32mm',
    cover: '/shop_img/bed_rail.jpg',
  },
  {
    id: 'p008',
    name: '适老记忆棉床垫',
    desc: '慢回弹记忆棉，适中硬度，透气防螨，保护脊椎',
    category: 'bedroom',
    price: 1580,
    originalPrice: 2180,
    tags: ['包邮'],
    specs: '厚度20cm / 1.5m/1.8m',
    cover: '/shop_img/mattress.jpg',
  },
  {
    id: 'p009',
    name: '感应夜灯（床头款）',
    desc: '人体感应自动亮灯，柔光不刺眼，磁吸充电，3档亮度',
    category: 'bedroom',
    price: 79,
    originalPrice: 119,
    tags: ['新品', '热销'],
    specs: '色温3000K / 续航8小时',
    cover: '/shop_img/bed_night_light.jpg',
  },

  // === 客厅安全 ===
  {
    id: 'p010',
    name: '适老助力沙发椅',
    desc: '电动助力起身，高密度海绵，防滑脚垫，宽大扶手',
    category: 'living',
    price: 2980,
    originalPrice: 3980,
    tags: ['包邮', '上门安装'],
    specs: '单电机 / 承重150kg',
    cover: '/shop_img/lift_chair.jpg',
  },
  {
    id: 'p011',
    name: '圆角茶几（适老款）',
    desc: '全圆角设计防磕碰，原木色温馨，稳固不摇晃，高度适中',
    category: 'living',
    price: 680,
    originalPrice: 880,
    tags: ['新品'],
    specs: '100×60×45cm / 橡胶木',
    cover: '/shop_img/round_coffee_table.jpg',
  },
  {
    id: 'p012',
    name: '走廊安全扶手（一字型）',
    desc: '实木+防滑PVC包覆，手感温润，长度可定制',
    category: 'living',
    price: 188,
    originalPrice: 268,
    tags: ['热销'],
    specs: '长度60/80/100cm / 高度75-85cm',
    cover: '/shop_img/corridor_handrail.jpg',
  },
  {
    id: 'p013',
    name: '防滑地垫（全屋套装）',
    desc: 'TPE环保材质，吸水防滑，可裁剪，走廊/门口/卫浴通用',
    category: 'living',
    price: 59,
    originalPrice: 89,
    tags: ['多规格'],
    specs: '40×60cm / 50×80cm / 60×90cm',
    cover: '/shop_img/anti_slip_mat.jpg',
  },

  // === 厨房适老 ===
  {
    id: 'p014',
    name: '下拉式橱柜收纳架',
    desc: '免弯腰取物，下拉缓冲，承重15kg，适配标准橱柜',
    category: 'kitchen',
    price: 358,
    originalPrice: 498,
    tags: ['新品'],
    specs: '宽60cm / 3层 / 承重15kg',
    cover: '/shop_img/pull_down_shelf.jpg',
  },
  {
    id: 'p015',
    name: '适老操作台面升降架',
    desc: '电动升降台面，适配不同身高，坐姿/站姿均可操作',
    category: 'kitchen',
    price: 1280,
    originalPrice: 1680,
    tags: ['推荐'],
    specs: '升降范围70-95cm / 宽80cm',
    cover: '/shop_img/lift_countertop.jpg',
  },
  {
    id: 'p016',
    name: '防滑厨房地垫',
    desc: '加厚缓震，久站不累，防油防水，易清洁',
    category: 'kitchen',
    price: 68,
    originalPrice: 98,
    tags: ['包邮'],
    specs: '50×150cm / 厚度8mm',
    cover: '/shop_img/kitchen_mat.jpg',
  },

  // === 智能照明 ===
  {
    id: 'p017',
    name: '人体感应走廊灯',
    desc: '微波雷达感应，3米探测距离，柔光夜灯，免布线粘贴安装',
    category: 'lighting',
    price: 49,
    originalPrice: 79,
    tags: ['热销', '多买优惠'],
    specs: '色温3000K / USB充电',
    cover: '/shop_img/motion_light.jpg',
  },
  {
    id: 'p018',
    name: '适老智能台灯',
    desc: '无极调光调色温，大按键遥控，定时关灯，护眼防眩光',
    category: 'lighting',
    price: 198,
    originalPrice: 298,
    tags: ['新品'],
    specs: '色温2700-6500K / 触控+遥控',
    cover: '/shop_img/smart_desk_lamp.jpg',
  },
  {
    id: 'p019',
    name: '声控夜灯套装（3只装）',
    desc: '声控+人体双感应，磁吸安装，低亮度不刺眼',
    category: 'lighting',
    price: 99,
    originalPrice: 159,
    tags: ['套装优惠'],
    specs: '3只装 / 磁吸底座',
    cover: '/shop_img/voice_night_light.jpg',
  },

  // === 辅助器具 ===
  {
    id: 'p020',
    name: '紧急呼叫器（一键SOS）',
    desc: '一键呼叫，防水设计，卧室/卫浴/走廊多点位安装',
    category: 'assist',
    price: 158,
    originalPrice: 228,
    tags: ['推荐', '包邮'],
    specs: '无线 / 信号覆盖100m²',
    cover: '/shop_img/emergency_call.jpg',
  },
  {
    id: 'p021',
    name: '适老助行器（折叠款）',
    desc: '铝合金轻量化，折叠收纳，高度可调，带储物包',
    category: 'assist',
    price: 388,
    originalPrice: 528,
    tags: ['热销'],
    specs: '承重120kg / 净重2.8kg',
    cover: '/shop_img/walker.jpg',
  },
  {
    id: 'p022',
    name: '适老放大镜指甲剪套装',
    desc: '3倍放大镜+指甲剪+指甲锉，防滑手柄，操作省力',
    category: 'assist',
    price: 39,
    originalPrice: 59,
    tags: ['实用小物'],
    specs: '放大镜直径5cm / 不锈钢刀头',
    cover: '/shop_img/nail_clipper_set.jpg',
  },
  {
    id: 'p023',
    name: '适老穿袜辅助器',
    desc: '免弯腰穿袜，适合关节炎/腰腿不便长者，操作简单',
    category: 'assist',
    price: 29,
    originalPrice: 49,
    tags: ['实用小物'],
    specs: '适用鞋码35-45',
    cover: '/shop_img/sock_aid.jpg',
  },
  {
    id: 'p024',
    name: '适老防走失定位手环',
    desc: 'GPS+北斗双模定位，电子围栏告警，一键SOS，7天续航',
    category: 'assist',
    price: 298,
    originalPrice: 398,
    tags: ['推荐', '包邮'],
    specs: 'IP67防水 / 1.3寸屏',
    cover: '/shop_img/gps_bracelet.jpg',
  },
];

export const getProductsByCategory = (category) => {
  if (category === 'all') return products;
  return products.filter((p) => p.category === category);
};

export const getProductById = (id) => products.find((p) => p.id === id);
