// 适老化改造 AI 工具注册表
export const tools = [
  // === 适老化评估 ===
  {
    id: 'aging-assessment',
    name: 'AI适老化评估',
    desc: '上传房屋照片，AI自动识别适老化风险点，生成评估报告',
    domain: 'interior',
    type: 'drawing',
    tags: ['核心'],
    icon: 'SafetyCertificateOutlined',
    params: ['image', 'elderAge', 'mobility'],
    cover: '/assets/tool-covers/assess.jpg',
  },
  {
    id: 'hazard-detect',
    name: 'AI安全隐患检测',
    desc: '智能识别地面湿滑、门槛高差、锐角家具等安全隐患',
    domain: 'interior',
    type: 'optimize',
    tags: ['核心'],
    icon: 'WarningOutlined',
    params: ['image', 'detectType'],
    cover: '/assets/tool-covers/hazard.jpg',
  },

  // === 旧房改造 ===
  {
    id: 'ai-old-house',
    name: 'AI旧房适老改造',
    desc: '上传旧房照片，AI一键生成适老化改造方案效果图',
    domain: 'interior',
    type: 'modify',
    tags: ['核心', 'Hot'],
    icon: 'HomeOutlined',
    params: ['image', 'style', 'prompt'],
    cover: '/assets/tool-covers/old-house.jpg',
  },
  {
    id: 'ai-style-convert',
    name: 'AI适老风格转换',
    desc: '一键将现有空间转换为适老化风格，温暖安全',
    domain: 'interior',
    type: 'convert',
    tags: [],
    icon: 'RetweetOutlined',
    params: ['image', 'targetStyle'],
    cover: '/assets/tool-covers/style-convert.jpg',
  },
  {
    id: 'ai-room-renovate',
    name: 'AI全屋适老翻新',
    desc: '全屋适老化翻新方案，涵盖地面、墙面、照明、收纳',
    domain: 'interior',
    type: 'modify',
    tags: ['Hot'],
    icon: 'ToolOutlined',
    params: ['image', 'renovateScope', 'style'],
    cover: '/assets/tool-covers/renovate.jpg',
  },

  // === 卫浴改造 ===
  {
    id: 'bathroom-barrier-free',
    name: 'AI无障碍卫浴改造',
    desc: '一键生成无障碍卫浴方案：防滑地面、安全扶手、坐式淋浴',
    domain: 'interior',
    type: 'modify',
    tags: ['核心'],
    icon: 'DashboardOutlined',
    params: ['image', 'bathType', 'style'],
    cover: '/assets/tool-covers/bathroom.jpg',
  },
  {
    id: 'bathroom-shower',
    name: 'AI淋浴房适老改造',
    desc: '坐式淋浴、恒温花洒、防滑座椅一体化方案',
    domain: 'interior',
    type: 'modify',
    tags: [],
    icon: 'ThunderboltOutlined',
    params: ['image', 'showerType'],
    cover: '/assets/tool-covers/shower.svg',
  },
  {
    id: 'bathroom-toilet',
    name: 'AI如厕区适老改造',
    desc: '智能马桶、起身扶手、紧急呼叫一体化设计',
    domain: 'interior',
    type: 'modify',
    tags: [],
    icon: 'SafetyOutlined',
    params: ['image', 'toiletType'],
    cover: '/assets/tool-covers/toilet.jpg',
  },

  // === 地面改造 ===
  {
    id: 'anti-slip-floor',
    name: 'AI防滑地面改造',
    desc: '智能推荐防滑材质，一键预览改造效果',
    domain: 'interior',
    type: 'modify',
    tags: ['核心'],
    icon: 'CompressOutlined',
    params: ['image', 'floorMaterial'],
    cover: '/assets/tool-covers/floor.svg',
  },
  {
    id: 'threshold-remove',
    name: 'AI门槛消除改造',
    desc: '消除地面高差，实现全屋无障碍通行',
    domain: 'interior',
    type: 'modify',
    tags: [],
    icon: 'MinusOutlined',
    params: ['image', 'thresholdType'],
    cover: '/assets/tool-covers/threshold.jpg',
  },

  // === 扶手与安全 ===
  {
    id: 'handrail-design',
    name: 'AI安全扶手设计',
    desc: '智能规划扶手位置与样式，走廊、卫浴、楼梯全覆盖',
    domain: 'interior',
    type: 'drawing',
    tags: ['核心'],
    icon: 'PullRequestOutlined',
    params: ['image', 'railLocation', 'style'],
    cover: '/assets/tool-covers/handrail.jpg',
  },
  {
    id: 'stair-safety',
    name: 'AI楼梯适老改造',
    desc: '防滑踏步、双侧扶手、照明提示一体化方案',
    domain: 'interior',
    type: 'modify',
    tags: [],
    icon: 'RiseOutlined',
    params: ['image', 'stairType'],
    cover: '/assets/tool-covers/stair.jpg',
  },

  // === 照明与智能 ===
  {
    id: 'ai-lighting',
    name: 'AI适老照明优化',
    desc: '感应夜灯、无眩光照明、色温调节，守护夜间安全',
    domain: 'interior',
    type: 'optimize',
    tags: [],
    icon: 'BulbOutlined',
    params: ['image', 'lightMode'],
    cover: '/assets/tool-covers/lighting.jpg',
  },
  {
    id: 'smart-home',
    name: 'AI智能家居适配',
    desc: '语音控制、紧急呼叫、跌倒检测等智能设备方案',
    domain: 'interior',
    type: 'drawing',
    tags: ['New'],
    icon: 'RobotOutlined',
    params: ['image', 'smartType'],
    cover: '/assets/tool-covers/smart-home.jpg',
  },
  {
    id: 'emergency-call',
    name: 'AI紧急呼叫布局',
    desc: '智能规划紧急呼叫按钮位置，覆盖卧室、卫浴、走廊',
    domain: 'interior',
    type: 'drawing',
    tags: [],
    icon: 'AlertOutlined',
    params: ['image', 'callType'],
    cover: '/assets/tool-covers/emergency.jpg',
  },

  // === 厨房改造 ===
  {
    id: 'kitchen-elderly',
    name: 'AI适老厨房改造',
    desc: '降低操作台面、防滑地面、下拉式收纳一体化方案',
    domain: 'interior',
    type: 'modify',
    tags: [],
    icon: 'CoffeeOutlined',
    params: ['image', 'kitchenType', 'style'],
    cover: '/assets/tool-covers/kitchen.jpg',
  },

  // === 卧室改造 ===
  {
    id: 'bedroom-elderly',
    name: 'AI适老卧室改造',
    desc: '床边扶手、感应夜灯、防滑地面、紧急呼叫',
    domain: 'interior',
    type: 'modify',
    tags: [],
    icon: 'CloudOutlined',
    params: ['image', 'bedType', 'style'],
    cover: '/assets/tool-covers/bedroom.jpg',
  },

  // === 户型与平面 ===
  {
    id: 'ai-floorplan-color',
    name: 'AI户型图适老标注',
    desc: '上传户型图，AI自动标注适老化改造要点和动线',
    domain: 'interior',
    type: 'drawing',
    tags: [],
    icon: 'BorderOutlined',
    params: ['image', 'colorMode', 'style'],
    cover: '/assets/tool-covers/floorplan.jpg',
  },
  {
    id: 'ai-interior-plan',
    name: 'AI适老平面设计',
    desc: '一键生成适老化室内平面布局方案',
    domain: 'interior',
    type: 'drawing',
    tags: ['New'],
    icon: 'LayoutOutlined',
    params: ['image', 'roomType', 'style'],
    cover: '/assets/tool-covers/interior-plan.jpg',
  },
  {
    id: 'plan-to-3d',
    name: '适老平面转三维透视',
    desc: '将适老化平面方案转换为立体透视图预览',
    domain: 'interior',
    type: 'convert',
    tags: [],
    icon: 'BlockOutlined',
    params: ['image', 'viewMode'],
    cover: '/assets/tool-covers/plan3d.jpg',
  },
  {
    id: 'wheelchair-path',
    name: 'AI轮椅动线规划',
    desc: '智能规划轮椅通行路线，确保转角和门宽满足需求',
    domain: 'interior',
    type: 'drawing',
    tags: ['核心'],
    icon: 'AimOutlined',
    params: ['image', 'doorWidth'],
    cover: '/assets/tool-covers/wheelchair.jpg',
  },

  // === 绘图与渲染 ===
  {
    id: 'ai-draw',
    name: 'AI适老效果图生成',
    desc: '文生图/图生图，快速生成适老化改造效果图',
    domain: 'interior',
    type: 'drawing',
    tags: [],
    icon: 'PictureOutlined',
    params: ['image', 'style', 'prompt', 'negativePrompt'],
    cover: '/assets/tool-covers/draw.jpg',
  },
  {
    id: 'ai-hand-draw',
    name: 'AI手绘方案生成',
    desc: '上传手绘草图，AI生成适老化改造效果图',
    domain: 'interior',
    type: 'drawing',
    tags: [],
    icon: 'EditOutlined',
    params: ['image', 'style', 'prompt'],
    cover: '/assets/tool-covers/hand-draw.jpg',
  },
  {
    id: 'ai-model-render',
    name: 'AI模型适老渲染',
    desc: '上传3D模型截图，AI渲染适老化改造效果图',
    domain: 'interior',
    type: 'drawing',
    tags: [],
    icon: 'CubeOutlined',
    params: ['image', 'renderMode', 'style'],
    subTools: ['精细模型', '体块模型', '精细白模'],
    cover: '/assets/tool-covers/model-render.jpg',
  },

  // === 改图工具 ===
  {
    id: 'ai-inpaint',
    name: 'AI局部适老改造',
    desc: '标记改造区域，AI精准生成适老化改造效果',
    domain: 'interior',
    type: 'modify',
    tags: [],
    icon: 'HighlightOutlined',
    params: ['image', 'mask', 'prompt'],
    cover: '/assets/tool-covers/inpaint.jpg',
  },
  {
    id: 'ai-material-replace',
    name: 'AI地面材质替换',
    desc: '一键替换地面材质，预览防滑木地板、防滑砖等效果',
    domain: 'interior',
    type: 'modify',
    tags: [],
    icon: 'BgColorsOutlined',
    params: ['image', 'material'],
    cover: '/assets/tool-covers/material.svg',
  },
  {
    id: 'ai-furniture-replace',
    name: 'AI适老家具替换',
    desc: '一键替换为圆角家具、适老床、助力椅等',
    domain: 'interior',
    type: 'modify',
    tags: [],
    icon: 'HomeOutlined',
    params: ['image', 'furniture'],
    cover: '/assets/tool-covers/furniture.jpg',
  },
  {
    id: 'ai-collage',
    name: 'AI适老设施拼贴',
    desc: '拼贴扶手、坡道、呼叫器等适老设施，AI融合生成',
    domain: 'interior',
    type: 'modify',
    tags: [],
    icon: 'AppstoreOutlined',
    params: ['image', 'materials', 'prompt'],
    cover: '/assets/tool-covers/collage.jpg',
  },
  {
    id: 'ai-detail-enhance',
    name: 'AI细节增强',
    desc: '增强效果图的适老化细节，如扶手纹理、防滑标识',
    domain: 'interior',
    type: 'modify',
    tags: [],
    icon: 'ZoomInOutlined',
    params: ['image', 'strength'],
    cover: '/assets/tool-covers/enhance.jpg',
  },

  // === 优化工具 ===
  {
    id: 'ai-atmosphere',
    name: 'AI温馨氛围优化',
    desc: '一键转换画面氛围，营造温暖安全的适老居住环境',
    domain: 'interior',
    type: 'optimize',
    tags: [],
    icon: 'CloudOutlined',
    params: ['image', 'atmosphere'],
    cover: '/assets/tool-covers/atmosphere.jpg',
  },
  {
    id: 'ai-shadow',
    name: 'AI适老光影优化',
    desc: '优化照明光影，消除眩光和阴影死角',
    domain: 'interior',
    type: 'optimize',
    tags: [],
    icon: 'SunOutlined',
    params: ['image', 'shadowMode'],
    cover: '/assets/tool-covers/shadow.jpg',
  },
  {
    id: 'ai-color-palette',
    name: '适老配色工具',
    desc: '高对比度、暖色调配色方案，方便老年人识别',
    domain: 'interior',
    type: 'optimize',
    tags: [],
    icon: 'FormatPainterOutlined',
    params: ['image', 'colorScheme'],
    cover: '/assets/tool-covers/palette.svg',
  },

  // === 转换工具 ===
  {
    id: 'ai-to-cad',
    name: 'AI图转CAD',
    desc: '适老改造方案图转标准CAD，支持分图层导出',
    domain: 'interior',
    type: 'convert',
    tags: [],
    icon: 'FileTextOutlined',
    params: ['image'],
    cover: '/assets/tool-covers/to-cad.jpg',
  },
  {
    id: 'cad-to-render',
    name: 'CAD转适老效果图',
    desc: '上传CAD平面图，一键生成适老化改造效果图',
    domain: 'interior',
    type: 'convert',
    tags: [],
    icon: 'FileOutlined',
    params: ['file'],
    cover: '/assets/tool-covers/cad-render.jpg',
  },

  // === 通用工具 ===
  {
    id: 'ai-erase',
    name: 'AI消除工具',
    desc: '去除图片中多余物体，为适老设施腾出空间',
    domain: 'interior',
    type: 'optimize',
    tags: [],
    icon: 'DeleteOutlined',
    params: ['image', 'mask'],
    cover: '/assets/tool-covers/erase.jpg',
  },
  {
    id: 'ai-hd',
    name: 'AI超清增强',
    desc: '模糊效果图一键提升清晰度',
    domain: 'interior',
    type: 'optimize',
    tags: [],
    icon: 'EyeOutlined',
    params: ['image', 'scale'],
    cover: '/assets/tool-covers/hd.jpg',
  },
  {
    id: 'ai-upscale',
    name: 'AI图片放大',
    desc: '2-8倍放大，保持画质高清',
    domain: 'interior',
    type: 'optimize',
    tags: [],
    icon: 'ExpandOutlined',
    params: ['image', 'scale'],
    cover: '/assets/tool-covers/upscale.jpg',
  },

  // === 智能体 ===
  {
    id: 'ai-design-agent',
    name: 'AI适老改造顾问',
    desc: '对话式适老化改造方案设计，专业建议一键出图',
    domain: 'interior',
    type: 'other',
    tags: ['核心', 'Hot'],
    icon: 'RobotOutlined',
    params: ['chat'],
    isAgent: true,
    cover: '/assets/tool-covers/agent.jpg',
  },
  {
    id: 'ai-canvas-agent',
    name: 'AI适老画布Agent',
    desc: '一站式适老化改造创作画布，拖拽式设计',
    domain: 'interior',
    type: 'other',
    tags: ['Hot'],
    icon: 'DashboardOutlined',
    params: ['canvas'],
    isAgent: true,
    cover: '/assets/tool-covers/canvas.jpg',
  },
  {
    id: 'ai-modify-agent',
    name: 'AI适老改图智能体',
    desc: '对话式修改适老化效果图，精准调整改造细节',
    domain: 'interior',
    type: 'other',
    tags: [],
    icon: 'MessageOutlined',
    params: ['chat', 'image'],
    isAgent: true,
    cover: '/assets/tool-covers/modify-agent.jpg',
  },
];

export const getToolsByDomain = (domain) => {
  if (domain === 'all') return tools;
  return tools.filter((t) => t.domain === domain);
};

export const getToolsByType = (type) => {
  if (type === 'all') return tools;
  return tools.filter((t) => t.type === type);
};

export const getToolById = (id) => tools.find((t) => t.id === id);

export const getToolGroups = () => {
  const groups = {};
  tools.forEach((t) => {
    if (!groups[t.type]) groups[t.type] = [];
    groups[t.type].push(t);
  });
  return groups;
};
